{{- if .Values.service.ports -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "microservice.chart" $ }}
    app.kubernetes.io/name: {{ include "microservice.name" $ }}
    app.kubernetes.io/instance: {{ include "microservice.fullname" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "microservice.name" $ }}
    app.kubernetes.io/part-of: {{ $.Release.Name }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .externalPort }}
      name: {{ .name }}
      targetPort: {{ .internalPort }}
    {{- end }}
{{- end }}