name: {{CMD}} - Test
on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'cmd/{{CMD}}/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'cmd/{{CMD}}/**'
jobs:
  test-{{CMD}}:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v2
      - name: Print Go version
        run: go version
      - name: Add and install dependencies
        run: |-
          cd cmd/{{CMD}}
          go get ./...
      - name: Examine source code
        run: |-
          cd cmd/{{CMD}}
          go vet ./...
      - name: Run tests
        run: |-
          cd cmd/{{CMD}}
          go test ./... -v -race -cover -tags=docker
