name: {{CMD}} - Test
on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'cmd/{{CMD}}/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'cmd/{{CMD}}/**'
jobs:
  test-{{CMD}}:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v2
      - name: Print Node version
        run: node -v
      - name: Print yarn version
        run: yarn -v
      - name: Install dependencies
        run: |-
          cd cmd/{{CMD}}
          yarn
      - name: Run tests
        run: |-
          cd cmd/{{CMD}}
          yarn test
