name: pkg - Test
on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'pkg/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'pkg/**'
jobs:
  test-pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v2
      - name: Print Go version
        run: go version
      - name: Add and install dependencies
        run: |-
          cd pkg
          go get ./...
      - name: Examine source code
        run: |-
          cd pkg
          go vet ./...
      - name: Run tests
        run: |-
          cd pkg
          go test ./... -v -race -cover -tags=docker
