name: user - Test
on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'cmd/user/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'cmd/user/**'
jobs:
  test-user:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v2
      - name: Print Go version
        run: go version
      - name: Add and install dependencies
        run: |-
          cd cmd/user
          go get ./...
      - name: Examine source code
        run: |-
          cd cmd/user
          go vet ./...
      - name: Run tests
        run: |-
          cd cmd/user
          go test ./... -v -race -cover -tags=docker
